'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Friend Class ChatGPT
    Friend Class My_Project
        Friend Class My
            Friend Class MySettings
                Friend Shared Function [Default]() As MySettings
                    Throw New NotImplementedException()
                End Function
            End Class
        End Class
    End Class
End Class
